export const TowerImages = {
  AdmiralBrickell: "towers/AdmiralBrickell.png",
  Adora: "towers/Adora.png",
  Alchemist: "towers/Alchemist.png",
  BananaFarm: "towers/BananaFarm.png",
  BeastHandler: "towers/BeastHandler.png",
  Benjamin: "towers/Benjamin.png",
  BombShooter: "towers/BombShooter.png",
  BoomerangMonkey: "towers/BoomerangMonkey.png",
  CaptainChurchill: "towers/CaptainChurchill.png",
  ChosenPrimaryHero: "towers/ChosenPrimaryHero.png",
  Corvus: "towers/Corvus.png",
  DartlingGunner: "towers/DartlingGunner.png",
  DartMonkey: "towers/DartMonkey.png",
  Druid: "towers/Druid.png",
  Desperado: "towers/Desperado.png",
  EngineerMonkey: "towers/EngineerMonkey.png",
  Etienne: "towers/Etienne.png",
  Ezili: "towers/Ezili.png",
  Geraldo: "towers/Geraldo.png",
  GlueGunner: "towers/GlueGunner.png",
  Gwendolin: "towers/Gwendolin.png",
  HeliPilot: "towers/HeliPilot.png",
  IceMonkey: "towers/IceMonkey.png",
  Mermonkey: "towers/Mermonkey.png",
  MonkeyAce: "towers/MonkeyAce.png",
  MonkeyBuccaneer: "towers/MonkeyBuccaneer.png",
  MonkeySub: "towers/MonkeySub.png",
  MonkeyVillage: "towers/MonkeyVillage.png",
  MortarMonkey: "towers/MortarMonkey.png",
  NinjaMonkey: "towers/NinjaMonkey.png",
  ObynGreenfoot: "towers/ObynGreenfoot.png",
  PatFusty: "towers/PatFusty.png",
  Psi: "towers/Psi.png",
  Quincy: "towers/Quincy.png",
  Rosalia: "towers/Rosalia.png",
  Sauda: "towers/Sauda.png",
  SniperMonkey: "towers/SniperMonkey.png",
  SpikeFactory: "towers/SpikeFactory.png",
  StrikerJones: "towers/StrikerJones.png",
  SuperMonkey: "towers/SuperMonkey.png",
  TackShooter: "towers/TackShooter.png",
  WizardMonkey: "towers/WizardMonkey.png",
  Skywarden: "towers/Skywarden.png"
};

export const TowerContainers = {
  Heroes: "towers/TowerContainerHero.png",
  Primary: "towers/TowerContainerPrimary.png",
  Military: "towers/TowerContainerMilitary.png",
  Magic: "towers/TowerContainerMagic.png",
  Support: "towers/TowerContainerSupport.png",
  Max: "towers/TowerMax.png",
  Blocked: "towers/Blocked.png"
};
