MODIFIERS = {
  "speedMultiplier": "Bloon Speed",
  "moabSpeedMultiplier": "Moab Speed",
  "bossSpeedMultiplier": "Boss Speed",
  "regrowRateMultiplier": "Regrow Rate",
  "bloons": "Ceramic Health",
  "moabs": "Moab Health",
  "boss": "Boss Health",
  "allCamo": "All Camo",
  "allRegen": "All Regen",
  "disableMK": "MK Disabled",
  "disableSelling": "No Selling",
  "abilityCooldownReductionMultiplier": "Ability Cooldown Rate",
  "noContinues": "No Continues",
  "maxTowers": " Tower Limit",
  "maxParagons": " Paragon Limit",
  "LeastCashUsed": " Cash Limit",
  "LeastTiersUsed": " Tiers Max",
  "disablePowers": "No Powers",
  "removeableCostMultiplier": "Removeable Cost"
}
